services:
  lichtblick:
    image: ghcr.io/lichtblick-suite/lichtblick:latest
    #image: crpi-6ty60rr45g7d9i1q.cn-shanghai.personal.cr.aliyuncs.com/voyance/lichtblick:latest
    container_name: lichtblick
    ports:
      - "8080:8080"
    restart: always
